using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using GetEQd.Audio;
using Microsoft.Win32;

namespace GetEQd.Systemwide
{
    /// <summary>What getEQd found when it looked for Equalizer APO.</summary>
    public sealed class ApoInstallation
    {
        public ApoInstallation(bool isInstalled, string? configDirectory, string message)
        {
            IsInstalled = isInstalled;
            ConfigDirectory = configDirectory;
            Message = message;
        }

        public bool IsInstalled { get; }
        public string? ConfigDirectory { get; }
        public string Message { get; }

        /// <summary>The file getEQd owns inside the APO config directory.</summary>
        public string? ManagedFilePath => ConfigDirectory == null
            ? null
            : Path.Combine(ConfigDirectory, ApoConfig.ManagedFileName);
    }

    /// <summary>
    /// Turns the live settings into Equalizer APO configuration text.
    ///
    /// This is the v0.3.0 "system-wide" route: getEQd does not filter other applications'
    /// audio itself. It writes configuration and Equalizer APO does the filtering, which
    /// costs nothing and needs no driver signing.
    ///
    /// The whole point is that the emitted text reproduces the curve on screen. That is why
    /// shelves are written as LSC/HSC with a dB-per-octave slope rather than LS/HS with a Q:
    /// the C form uses the frequency directly as the RBJ center frequency and takes the same
    /// slope parameter getEQd's own Biquad uses, while the plain form applies a DCX2496
    /// corner-frequency correction and would quietly give a different response.
    ///
    /// Everything here is pure and unit tested. The registry lookup and the file write are
    /// the only parts that touch the machine, and they are kept at the edges.
    /// </summary>
    public static class ApoConfig
    {
        public const string ManagedFileName = "geteqd.txt";
        public const string IncludeLine = "Include: geteqd.txt";

        private static readonly CultureInfo Invariant = CultureInfo.InvariantCulture;

        /// <summary>The header line the documentation shows, and the one to keep first.</summary>
        public const string HeaderLine = "# Generated by getEQd. Edits here are overwritten.";

        public static string Build(EqSnapshot snapshot, int sampleRate)
        {
            HeadroomAnalysis headroom = Analysis.Evaluate(snapshot, sampleRate);

            StringBuilder text = new StringBuilder();
            text.Append(HeaderLine).Append('\n');
            text.Append("# getEQd ").Append(AppVersion()).Append(" · ")
                .Append(sampleRate).Append(" Hz · ")
                .Append(ActiveBandCount(snapshot)).Append(" of ").Append(Bands.Count)
                .Append(" bands active").Append('\n');

            // One preamp line, from the same number the console already shows the listener.
            text.Append("Preamp: ").Append(Format(headroom.SuggestedPreampDb, "0.0")).Append(" dB").Append('\n');

            int number = 0;
            for (int i = 0; i < snapshot.Enabled.Length; i++)
            {
                if (!snapshot.Enabled[i]) continue;

                number++;
                text.Append("Filter ").Append(number).Append(": ON ")
                    .Append(FilterLine(snapshot.Kinds[i], snapshot.Frequencies[i], snapshot.Qs[i], snapshot.Gains[i], sampleRate))
                    .Append('\n');
            }

            return text.ToString();
        }

        /// <summary>One band as a config line body, without the Filter prefix.</summary>
        public static string FilterLine(BandKind kind, double frequency, double q, double gainDb, int sampleRate)
        {
            double clampedFrequency = ClampFrequency(frequency, sampleRate);
            double clampedQ = ClampQ(q);
            string f = Format(clampedFrequency, "0.##");

            switch (kind)
            {
                case BandKind.LowShelf:
                    return "LSC " + Format(ShelfSlopeDbPerOctave(clampedQ), "0.0") + " dB Fc " + f +
                           " Hz Gain " + FormatSigned(gainDb);
                case BandKind.HighShelf:
                    return "HSC " + Format(ShelfSlopeDbPerOctave(clampedQ), "0.0") + " dB Fc " + f +
                           " Hz Gain " + FormatSigned(gainDb);
                case BandKind.LowPass:
                    return "LPQ Fc " + f + " Hz Q " + Format(clampedQ, "0.00");
                case BandKind.HighPass:
                    return "HPQ Fc " + f + " Hz Q " + Format(clampedQ, "0.00");
                case BandKind.Notch:
                    return "NO Fc " + f + " Hz Q " + Format(clampedQ, "0.00");
                default:
                    return "PK Fc " + f + " Hz Gain " + FormatSigned(gainDb) +
                           " Q " + Format(clampedQ, "0.00");
            }
        }

        /// <summary>
        /// getEQd designs shelves with the RBJ slope parameter S. Equalizer APO's LSC/HSC
        /// take dB per octave and divide by 12 to get that same S, so this is the conversion
        /// that keeps the two filters identical.
        /// </summary>
        public static double ShelfSlopeDbPerOctave(double q) => 12.0 * ShelfSlopeFromQ(q);

        /// <summary>Mirrors Biquad's own mapping so the emitted slope is the designed one.</summary>
        private static double ShelfSlopeFromQ(double q) => Math.Max(0.1, Math.Min(1.0, 0.5 + q * 0.5));

        /// <summary>Mirrors Biquad.ForBand's clamping, so the line carries the used value.</summary>
        public static double ClampFrequency(double frequency, int sampleRate) =>
            Math.Max(20.0, Math.Min(sampleRate * 0.45, frequency));

        public static double ClampQ(double q) => Math.Max(0.2, Math.Min(8.0, q));

        private static int ActiveBandCount(EqSnapshot snapshot)
        {
            int count = 0;
            foreach (bool enabled in snapshot.Enabled)
            {
                if (enabled) count++;
            }

            return count;
        }

        private static string AppVersion()
        {
            Version? version = typeof(ApoConfig).Assembly.GetName().Version;
            return version == null ? "0.0.0" : version.ToString(3);
        }

        private static string Format(double value, string format) =>
            value.ToString(format, Invariant);

        /// <summary>Gain always carries its sign, matching the documented examples.</summary>
        private static string FormatSigned(double gainDb) =>
            gainDb.ToString("+0.0;-0.0;0.0", Invariant) + " dB";

        // ================================================================ machine edges

        /// <summary>
        /// Reads where Equalizer APO keeps its configuration. Reads only: getEQd must never
        /// write to HKLM, and it must not create a config directory that is not there.
        /// </summary>
        public static ApoInstallation Detect()
        {
            try
            {
                string? configPath = ReadRegistryString(@"SOFTWARE\EqualizerAPO", "ConfigPath");
                if (!string.IsNullOrWhiteSpace(configPath) && Directory.Exists(configPath))
                {
                    return new ApoInstallation(true, configPath!, "Equalizer APO is installed.");
                }

                string? installPath = ReadRegistryString(@"SOFTWARE\EqualizerAPO", "InstallPath");
                if (!string.IsNullOrWhiteSpace(installPath))
                {
                    string fallback = Path.Combine(installPath!, "config");
                    if (Directory.Exists(fallback))
                    {
                        return new ApoInstallation(true, fallback, "Equalizer APO is installed.");
                    }
                }

                return new ApoInstallation(
                    false,
                    null,
                    "Equalizer APO is not installed, so there is nowhere to write a system-wide configuration yet.");
            }
            catch (Exception error)
            {
                return new ApoInstallation(false, null, "Could not read the Equalizer APO settings: " + error.Message);
            }
        }

        private static string? ReadRegistryString(string keyPath, string valueName)
        {
            using RegistryKey? key = Registry.LocalMachine.OpenSubKey(keyPath);
            return key?.GetValue(valueName) as string;
        }

        /// <summary>
        /// Writes the managed file and makes sure config.txt includes it exactly once.
        ///
        /// Idempotent on purpose: a second run must not stack a second Include line. Returns
        /// the path written.
        /// </summary>
        public static string Write(string configDirectory, EqSnapshot snapshot, int sampleRate)
        {
            string managedPath = Path.Combine(configDirectory, ManagedFileName);
            File.WriteAllText(managedPath, Build(snapshot, sampleRate), new UTF8Encoding(false));

            string entryPath = Path.Combine(configDirectory, "config.txt");
            string existing = File.Exists(entryPath) ? File.ReadAllText(entryPath) : string.Empty;
            if (!HasInclude(existing))
            {
                string separator = existing.Length == 0 || existing.EndsWith("\n", StringComparison.Ordinal)
                    ? string.Empty
                    : "\n";
                File.AppendAllText(entryPath, separator + IncludeLine + "\n", new UTF8Encoding(false));
            }

            return managedPath;
        }

        /// <summary>True when config.txt already pulls in the managed file.</summary>
        public static bool HasInclude(string configText)
        {
            foreach (string line in configText.Split('\n'))
            {
                string trimmed = line.Trim().TrimEnd('\r');
                if (trimmed.StartsWith("Include:", StringComparison.OrdinalIgnoreCase) &&
                    trimmed.Substring("Include:".Length).Trim()
                        .Equals(ManagedFileName, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Removes getEQd's file and its include line. Uninstalling must do this: otherwise
        /// the machine keeps applying the last curve with no console to change it.
        /// </summary>
        public static void Remove(string configDirectory)
        {
            string managedPath = Path.Combine(configDirectory, ManagedFileName);
            if (File.Exists(managedPath)) File.Delete(managedPath);

            string entryPath = Path.Combine(configDirectory, "config.txt");
            if (!File.Exists(entryPath)) return;

            List<string> kept = new List<string>();
            foreach (string line in File.ReadAllLines(entryPath))
            {
                string trimmed = line.Trim();
                if (trimmed.StartsWith("Include:", StringComparison.OrdinalIgnoreCase) &&
                    trimmed.Substring("Include:".Length).Trim()
                        .Equals(ManagedFileName, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                kept.Add(line);
            }

            File.WriteAllLines(entryPath, kept, new UTF8Encoding(false));
        }

        // ================================================================ headless mode

        /// <summary>
        /// Prints the configuration this build would write, without writing it anywhere
        /// unless asked:
        ///
        ///   getEQd.exe --apo-config
        ///   getEQd.exe --apo-config --preset impact --out config.txt
        ///   getEQd.exe --apo-config --sample-rate 32000
        ///
        /// This is how the emitted text is inspected on a machine that does not have
        /// Equalizer APO installed.
        /// </summary>
        public static int Run(string[] args, TextWriter output)
        {
            string preset = "reference";
            string? outPath = null;
            int sampleRate = 48000;

            for (int i = 1; i < args.Length - 1; i++)
            {
                if (string.Equals(args[i], "--preset", StringComparison.OrdinalIgnoreCase)) preset = args[i + 1];
                if (string.Equals(args[i], "--out", StringComparison.OrdinalIgnoreCase)) outPath = args[i + 1];
                if (string.Equals(args[i], "--sample-rate", StringComparison.OrdinalIgnoreCase) &&
                    int.TryParse(args[i + 1], NumberStyles.Integer, CultureInfo.InvariantCulture, out int parsed) &&
                    parsed >= 8000 && parsed <= 384000)
                {
                    sampleRate = parsed;
                }
            }

            if (Presets.Find(preset) == null)
            {
                output.WriteLine("Unknown preset '" + preset + "'. Try reference, impact, dialogue, or night.");
                return 2;
            }

            EqSettings settings = new EqSettings();
            settings.ApplyPreset(preset);
            EqSnapshot snapshot = settings.CreateSnapshot();
            string config = Build(snapshot, sampleRate);

            ApoInstallation installation = Detect();
            output.WriteLine("getEQd system-wide configuration");
            output.WriteLine("  preset          : " + preset);
            output.WriteLine("  sample rate     : " + sampleRate + " Hz");
            output.WriteLine("  equalizer apo   : " + installation.Message);
            if (installation.ConfigDirectory != null)
            {
                output.WriteLine("  config directory: " + installation.ConfigDirectory);
            }
            output.WriteLine();
            output.WriteLine(config);

            if (outPath != null)
            {
                File.WriteAllText(outPath, config, new UTF8Encoding(false));
                output.WriteLine("Written to " + outPath);
            }

            return 0;
        }
    }
}
